yml changed

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -33,7 +33,7 @@ jobs:
         run: |
           SCORE_LIMIT=9.9
           BASE=$(git merge-base origin/master HEAD)
-          FILES=$(git diff --name-only --diff-filter=ACMR $BASE...HEAD | grep '\.py'$ || true)
+          FILES=$(git diff --name-only --diff-filter=ACMR $BASE...HEAD | grep '\.py$' | paste -sd' ' - || true)
           if [ -z "$FILES" ]; then
             echo "No python files has been changed, skipping linter"
           else
@@ -41,7 +41,12 @@ jobs:
             SCORE=$(pylint $FILES | grep 'Your code has been rated' | awk '{print $7}' | cut -d'/' -f1)
             echo "Static check score: $SCORE/10.0 - required: $SCORE_LIMIT"
             COMPARE=$(echo "$SCORE < $SCORE_LIMIT" | bc -l)
+            echo "Raw pylint output:"
+            cat pylint.log
+            echo "Parsed SCORE: $SCORE"
+            echo "Compare result: $COMPARE"
             if [ "$COMPARE" -eq 1 ]; then 
-              echo "Code rating below threshold. Failing the job." exit 1; 
-            fi;
-          fi;
+              echo "Code rating below threshold. Failing the job." 
+              exit 1 
+            fi
+          fi
