Add code rating

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -17,10 +17,20 @@ jobs:
         with:
           python-version: 3.11.6
 
-      - name: Install linter
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip 
           pip install -r requirements.txt
+          sudo apt-get update && sudo apt-get install -y bc
 
-      - name: Run linter
-        run: pylint budget_app/admin.py
+      - name: Run linter and get results
+        run: |
+          SCORE=$(pylint budget_app/admin.py | grep 'Your code has been rated' | awk '{print $7}' | cut -d'/' -f1)
+          LIMIT=9.9
+          COMPARE=$(echo "$SCORE < $LIMIT" | bc)
+          if [ "$COMPARE" -eq 1 ]; then
+            echo "Static check rating is too low: $SCORE/10.0 - required: $LIMIT"
+            exit 1
+          else
+            echo "Static check rating is OK ($SCORE/10.0)"
+          fi
